services:
  caddy:
    build:
      context: .
      dockerfile: ./caddy/Dockerfile
    container_name: usermanagement_caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - uploads_volume:/usr/share/caddy/uploads
    networks:
      - app-network
    restart: unless-stopped
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: usermanagement_backend
    env_file: .env
    volumes:
      - db_volume:/app/data
      - uploads_volume:/app/uploads
    networks:
      - app-network
    restart: unless-stopped
    depends_on:
      - db-init

  db-init:
    build:
      context: ./backend
      dockerfile: Dockerfile.db
    container_name: usermanagement_db_init
    env_file: .env
    volumes:
      - db_volume:/app/data
    networks:
      - app-network
    command: node init-db.js

networks:
  app-network:
    driver: bridge

volumes:
  db_volume:
    driver: local
  uploads_volume:
    driver: local
